"""first migration

Revision ID: 1c470d87aa6c
Revises: 
Create Date: 2022-10-31 16:53:54.788140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1c470d87aa6c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "current_data",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("place", sa.String(length=255), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "weather_apis",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column(
            "create_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("api_url", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather_apis")
    op.drop_table("current_data")
    # ### end Alembic commands ###
