"""add more columns

Revision ID: 5f3417c6e51f
Revises: 1c470d87aa6c
Create Date: 2022-10-31 17:38:57.117560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f3417c6e51f"
down_revision = "1c470d87aa6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "current_data", sa.Column("weather_api_pk", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "current_data", "weather_apis", ["weather_api_pk"], ["pk"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "current_data", type_="foreignkey")
    op.drop_column("current_data", "weather_api_pk")
    # ### end Alembic commands ###
